info:
  author: kiran from dev
  version: 2.0

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
    
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
